<!--Desarrollado por david beltrán-->
<!doctype html>
<html>
    <head>
        <title>Crud Phalcon</title>
        <link rel="stylesheet" href="archivos/css/bootstrap.css"/>
        <link rel="stylesheet" href="archivos/font-awesome/css/font-awesome.min.css"/>
    </head>
    <body ng-app="index-modulo" ng-controller="indexController as inc">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-header">
               <a title="Crud Phalcon Framework" class="navbar-brand" href="#"><i class = "fa fa-desktop" ></i> CPHF</a>
            </div>
            <div id="navbarCollapse" class="collapse navbar-collapse navbar-ex1-collapse">
            </div>  
            <div style="background-color:#ff4524;width:34%;height:5px;float:left;" ></div>  
            <div style="background-color:#fff;width:32%;height:5px;float:left;" ></div>
            <div style="background-color:#579d1c;width:34%;height:5px;float:left;" ></div>
        </div>
        <div style="padding: 60px;"></div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        <form ng-submit="inc.enviar()" method="POST" class="form-horizontal">
                            <fieldset>
                                <legend><i class="fa fa-user"></i> Formulario</legend>
                                <div class="form-group">
                                    <label class="col-sm-12">Ingrese su nombre:</label>
                                    <div class="col-sm-12">
                                        <input ng-model="inc.data.nombre" placeholder="Ingrese su nombre" required type="text" name="nombre" class="form-control">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-12">Ingrese su mensaje:</label>
                                    <div class="col-sm-12">
                                        <textarea ng-model="inc.data.mensaje" placeholder="Ingrese su mensaje" required type="text" name="mensaje" class="form-control"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <button type="reset" class="btn btn-default"><i class="fa fa-file"></i> Nuevo</button>
                                        &nbsp;
                                        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Guardar</button>
                                    </div>    
                                </div>
                            </fieldset>
                        </form>
                    </div>
                    <div class="col-sm-1"></div>
                    <div class="col-sm-6">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h5>Mensajes</h5>
                            </div>
                            <div class="panel-body">
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
        <script src="archivos/js/angular.js"></script>
        <script src="archivos/js/angular-animate.js"></script>
        <script src="archivos/js/angular-touch.js"></script>
        <script src="archivos/js/angular-sanitize.js"></script>
        <script src="archivos/js/ui-bootstrap-tpls-1.2.4.js"></script>
        <script src="archivos/js/index.js"></script>
</html>

